# Generated by Django 4.0.3 on 2022-03-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_autor_post_alter_post_categoria_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagem_post',
            new_name='post_img',
        ),
    ]
