# Generated by Django 4.0.3 on 2022-03-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_imagem_post_post_post_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_img',
            new_name='img_post',
        ),
    ]
